#!/bin/bash

export WCOPRECO_BASEDIR=$(pwd)
export WCOPRECO_BUILDDIR=${WCOPRECO_BASEDIR}/build
export WCOPRECO_INCDIR=${WCOPRECO_BUILDDIR}/include
export WCOPRECO_LIBDIR=${WCOPRECO_BUILDDIR}/lib
export WCOPRECO_BINDIR=${WCOPRECO_BUILDDIR}/bin

[[ ":$LD_LIBRARY_PATH:" != *":${WCOPRECO_LIBDIR}:"* ]] && export LD_LIBRARY_PATH="${WCOPRECO_LIBDIR}:${LD_LIBRARY_PATH}"
[[ ":$PATH:" != *":${WCOPRECO_BINDIR}:"* ]] && export PATH="${WCOPRECO_BINDIR}:${PATH}"


